name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          repository: linuxdeepin/linglong-builder-demo

      - name: ll-builder-build
        uses: guanzi008/linglong-builder-action@main
